source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in flex.gemspec.
gemspec

gem "puma"

gem "sqlite3"

gem "sprockets-rails"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"

group :development, :test do
  gem "shoulda-matchers", "~> 6.0"
  gem "rspec-rails", "~> 7.0.0"
end

group :development do
  # Linting
  gem "rubocop-rails-omakase", require: false
  gem "rubocop-rspec", require: false
end
